[metadata]
name = solvent-evaporation
version = attr: solvent_evaporation.__version__
description = Simple numerical model for capturing two-component solvent evaporation
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/mayukh33/solvent-evaporation
project_urls =
    Source Code = https://github.com/mayukh33/solvent-evaporation
    Issue Tracker = https://github.com/mayukh33/solvent-evaporation/issues
classifiers =
    Intended Audience :: Science/Research
    Topic :: Scientific/Engineering :: Chemistry
    Topic :: Scientific/Engineering :: Physics
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Programming Language :: Python :: 3.13
    Programming Language :: Python :: 3.14

[options]
packages = find:
package_dir =
    = src
python_requires = >=3.10
install_requires =
    numpy
    scipy

[options.packages.find]
where = src

[options.extras_require]
numba =
    numba
